# Generated by Django 5.2.17 on 2026-08-11 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SENT', 'Enviada'), ('REVIEW', 'En revisión'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('PAUSED', 'Pausada'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='internship', to='internships.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='companies.company')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='companies.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='internships/evidences/')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('result', models.CharField(default='PENDING', max_length=30)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='internships/certificates/')),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('modality', models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('REMOTE', 'Remota'), ('HYBRID', 'Híbrida')], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CLOSED', 'Cerrada'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='institutions.technicalcareer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='companies.company')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='institutions.institution')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.opportunity'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('cv', models.FileField(blank=True, null=True, upload_to='students/cv/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='students/portfolio/')),
                ('is_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institutions.technicalcareer')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='internships.studentprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('opportunity', 'student'), name='unique_student_opportunity'),
        ),
    ]
